### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jisungbin** [GitMessengerBot/GitMessengerBot-Android#7]
- [ ] 노티피케이션에 봇 On/Off 버튼 넣기
- [ ] 스크립트 설정 디자인
- [ ] 깃 메인 기능(Commit and Push) 제작
- [ ] Kaven 제작
- [ ] ... 추후 더 추가

**Comment by nolbo** [comment]
커스텀 신텍스 하이라이트

**Comment by jisungbin** [comment]
@nolbo 불가능

**Comment by nolbo** [comment]
쏴룽해요
